### PR TITLE
use JSON-java @48d31b7f5c8e43321e4b2143a8a795c366ace6d9

### PR DESCRIPTION
**Pull request by maflcko**
Though, it seems the "Download ZIP" or "Source code (.tar.gz)" (by GitHub) is no longer working properly and the json folder is empty. Thus, `git clone -b master --recursive https://github.com/...` is needed...

### CODE REVIEW

**Comment by Rillke** [comment]
Then make Ant downloading required dependencies on demand. Something like https://github.com/Toollabs/validator/blob/master/java/css-validator/build.xml#L52 should do the job.

**Comment by maflcko** [comment]
Connecting to the internet during a build seems wrong to me. Having a "hard-copy" in the source appears the best solution to me right now.

**Comment by maflcko** [comment]
We should use a subtree instead. Force pushed subtree-commit. (Old commit: 7bf1d0e)

Note:

```
git subtree [add/pull] --prefix org/json/ json-java 48d31b7f5c8e43321e4b2143a8a795c366ace6d9  --squash
```

**Comment by Rillke** [comment]
Have you had a look into the `Files changed` tab? Looks like some file modes changed. Also, is it possible to just squash all 3 commits into a single one? (To be honest, I have no clue about subtrees, yet so don't give too much on what I comment.)

Apart from that, it looks like The Solution(TM).

**Comment by maflcko** [comment]
First commit is from me. The others are from subtree. Of course you could squash them but this makes `git subtree pull` in the future not possible. (Needs a `git subtree add` again).

I suspect the file mode changes originate from the json-java repo. Basically the got +x everywhere: Even though, this does not make any sense it also can't cause damage?

**Comment by maflcko** [comment]
Meh, we don't need a subtree. I removed the x-permission and some files in 0573d1fbafd815109e20605d44c64e728920600c and then force pushed everything squashed together.

**Pull request merged**
