### PR TITLE
Clarify sign up process

### PR DESCRIPTION
**Pull request by maflcko**
- New users automatically sign up at https://commons.wikimedia.org/wiki/Commons:GlobalReplace/Sign-in if they are allowed to do so. (Right now every autoconfirmed user can do so)
- Rejected users can request sign up on the talk page of mentioned page

### CODE REVIEW

**Comment by maflcko** [comment]
@Rillke should I just merge if the Travis CI build passed?

**Comment by revi** [comment]
That would defeat the purpose of the code review - code review by other than its author.

**Comment by Rillke** [comment]
> @Rillke should I just merge if the Travis CI build passed?
> 
> > That would defeat the purpose of the code review - code review by other than its author.

CI only checks that it compiles, at the moment. I am still thinking about making it somehow smoke test the whole tool that was built; but since it's a GUI tool, it might be difficult.

As long as you test the tool after merging, it should be fine. I have not really time to do code review at the moment and we are not breaking anything running on Commons...

**Comment by maflcko** [comment]
If someone wants to review this: I was only doing code cleanup/format/refactor... and the only functional change was that user now are required to sign up for using the tool.

This works by adding their name to the edit protected wiki page: https://commons.wikimedia.org/w/index.php?title=Commons:GlobalReplace/Sign-in&action=history

**Pull request merged**
