### PR TITLE
Warn on text==null

### PR DESCRIPTION
**Pull request by maflcko**
@fastily Please take a look here. The jar library seems broken.

### CODE REVIEW

**Comment by fastily** [comment]
Could you please clarify what you meant by 'broken'?  If you want to verify that a page exists, please use the `Wiki::exists()` method.  `Wiki::getPageText()` appropriately [returns an empty string](https://fastily.github.io/jwiki/docs/jwiki/jwiki/core/Wiki.html#getPageText-java.lang.String-) if the page does not exist.

**Comment by maflcko** [comment]
When the method never returns `null`, why is there a check in the code to see if the string is null?

Also, I the warning I added in this pull triggers:

```
Mar 01, 2016 01:26:29 PM
INFO: [32m[--- @ commons.wikimedia.org]: Getting global usage for File:CA Bastia.png[0m
Mar 01, 2016 01:26:29 PM
FYI: [36m[--- @ commons.wikimedia.org]: Get Wiki for --- @ pt.wikipedia.org[0m
Mar 01, 2016 01:26:29 PM
INFO: [32m[--- @ pt.wikipedia.org]: Getting page text of Cercle_Athlétique_Bastiais[0m
Mar 01, 2016 01:26:30 PM
WARNING: [33mCould not find text of Cercle_Athlétique_Bastiais[0m
```

**Comment by fastily** [comment]
Ok, I was able to reproduce the error.  It's caused by MediaWiki auto-normalizing malformed titles; for example, `file:test_File.jpg` is normalized to `File:Test File.jpg` which causes null to be returned because the returned map from RSet then keys the result of `file:test_File.jpg` to `File:Test File.jpg`. I'll look into a fix for this.  

Going to go ahead and merge the pull for now since it helps to alleviate the problem

**Comment by maflcko** [comment]
Also, I have observed that GlobalReplace will crash if the user does not upper case the first character of the file to be replaced. `Wiki.java` is using https://github.com/MER-C/wiki-java/blob/27d33a9d1cfa306fadada9f45a258a885fe1cf49/src/org/wikipedia/Wiki.java#L630 to `normalize()` Strings but I am not sure how your library handles this case.

**Comment by fastily** [comment]
jwiki does not handle auto-normalization by the API explicitly, so I'm rewriting RSet to handle this.  In the mean time, you could enable GlobalReplace, and add several try-catch blocks for null pointer exceptions, warning users that text fields are case-sensitive and may not contain underscores.

**Comment by maflcko** [comment]
IIRC, it didn't even work when I put in the name correctly capitalized.

**Comment by fastily** [comment]
Could you please provide an example/code snippet of that case which crashed jwiki so I can fix it?

**Comment by maflcko** [comment]
~~So maybe this "underscore thing" and "fist letter small" is an issue with GR and not jwiki?~~

**Comment by maflcko** [comment]
I'd prefer if the normalization is done by jwiki and not GR, so we won't have this issue in the first place.

Anyway, the code to reproduce my above issue:

``` java

wiki = wiki.getWiki("pt.wikipedia.org");
System.out.println(wiki.getPageText("Cercle_Athlétique_Bastiais") != null);
```

which prints `false` on my machine.

**Comment by maflcko** [comment]
The other code is 

``` java
wiki = wiki.getWiki("commons.wikimedia.org");
System.out.println(wiki.globalUsage("File:CA BastiaT.png"));
System.out.println(wiki.globalUsage("File:cA BastiaT.png"));
System.out.println(wiki.globalUsage("File:cA_BastiaT.png"));
```

which prints 

```
{}
null
null
```

on my machine

**Comment by fastily** [comment]
Thanks!  I'm aware of the strange behavior caused by titles with non-standard capitalization or underscores; the changes I'm working on will definitely handle these cases.

I was just worried that there was another case that I didn't know about which was causing exceptions.

**Comment by maflcko** [comment]
@fastily Any progress on this issue?

**Comment by fastily** [comment]
Please note that this isn't a trivial feature request you're asking for, since it does involve a rewrite of the core results parsing module (RSet); I did not originally intend for jwiki to handle bad inputs as that really should be a task for the client.  

If you're in a hurry to get GlobalReplace back online, then please consider adding JOptionPanes to warn the user when entering in non-standard titles (i.e. containing underscores and strange capitalization).  If the user is using copy+paste to enter titles (most are) then this won't be frequently displayed warning anyways.

**Comment by maflcko** [comment]
Thanks for the update. Normalizing the name on the client side should be trivial. I am happy to do that.

Still, about the actual issue I tried to debug in this pull:

``` java
wiki = wiki.getWiki("pt.wikipedia.org");
System.out.println(wiki.getPageText("Cercle_Athlétique_Bastiais") != null);
```

Any Idea what is causing this and how it could be resolved? IIrc, the page name is the result of `globalReplace()`, so maybe a bug in the lib?

Edit: It seems odd to work around that in the client, if it is even possible.

**Comment by fastily** [comment]
That snippet prints `false` for me too.  I suppose that is expected, because the result map constructed by RSet is directly derived from the JSON returned by the API, so it won't contain a key for the non-normalized title.

How about checking if the result of `getPageText()` is null, and then displaying a dialog to warn the user?

**Comment by maflcko** [comment]
> non-normalized title

This is the title which is returned by jwiki (`globalUsage()`). I can't find a reason why a client would have to normalize a title returned by the library before passing it on to the library again?

Edit: You could try with the following file: `File:CA BastiaT.jpg`.

**Pull request merged**
