### PR TITLE
Capitalize first user name letter

### PR DESCRIPTION
**Pull request by Rillke**
to avoid different spellings of the same user on the registration page

### CODE REVIEW

**Comment by maflcko** [comment]
I'd rather fix this in the core https://github.com/Commonists/GlobalReplace/blob/d7162c01f052c4351621062a34a114ee076b0e37/fbot/lib/core/Wiki.java#L17

Otherwise you end up fixing every `wiki.whoami()`

**Comment by Rillke** [comment]
> I'd rather fix this in the core

I thought it's a library? Do you have commit access to the repo which hosts the library?

**Comment by maflcko** [comment]
No, I could not find any traces of https://github.com/MER-C/wiki-java

This seems indeed the lib created by Fastily.

**Comment by Rillke** [comment]
Okay, you'll fix the library. Thanks :)

**Pull request closed without merging**
